@startuml
!theme plain
hide footbox
actor User
participant Logic
participant FilterTimeslotCommandParser
participant FilterTimeslotCommand
participant Model

User -> Logic : execute("filtertimeslot sd/...")
activate Logic
Logic -> FilterTimeslotCommandParser : parse("sd/...")
activate FilterTimeslotCommandParser
Logic <-- FilterTimeslotCommandParser : cmd:FilterTimeslotCommand
deactivate FilterTimeslotCommandParser

Logic -> FilterTimeslotCommand : execute(model)
activate FilterTimeslotCommand
FilterTimeslotCommand -> Model : updateFilteredPersonList(predicate)
activate Model
deactivate Model

Logic <-- FilterTimeslotCommand : result:CommandResult
deactivate FilterTimeslotCommand

User <-- Logic : result
deactivate Logic
@enduml
